// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwizP6NENAp79JsZJnRyRjwcqQ6BDWP4o',
    appId: '1:317686517862:web:01b9a9944b3e4665fa1da7',
    messagingSenderId: '317686517862',
    projectId: 'dietapro-f1b95',
    authDomain: 'dietapro-f1b95.firebaseapp.com',
    storageBucket: 'dietapro-f1b95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo1DCK7KqRABoWnVYLGtO36xOZ3eJKQ68',
    appId: '1:317686517862:android:9526779585902c78fa1da7',
    messagingSenderId: '317686517862',
    projectId: 'dietapro-f1b95',
    storageBucket: 'dietapro-f1b95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUH6bNSTdwYqBtVC6DL0T8ooCXuGVn4cM',
    appId: '1:317686517862:ios:83560e095e753fd7fa1da7',
    messagingSenderId: '317686517862',
    projectId: 'dietapro-f1b95',
    storageBucket: 'dietapro-f1b95.firebasestorage.app',
    iosBundleId: 'com.example.dietapro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUH6bNSTdwYqBtVC6DL0T8ooCXuGVn4cM',
    appId: '1:317686517862:ios:83560e095e753fd7fa1da7',
    messagingSenderId: '317686517862',
    projectId: 'dietapro-f1b95',
    storageBucket: 'dietapro-f1b95.firebasestorage.app',
    iosBundleId: 'com.example.dietapro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwizP6NENAp79JsZJnRyRjwcqQ6BDWP4o',
    appId: '1:317686517862:web:a4311d491aaf7695fa1da7',
    messagingSenderId: '317686517862',
    projectId: 'dietapro-f1b95',
    authDomain: 'dietapro-f1b95.firebaseapp.com',
    storageBucket: 'dietapro-f1b95.firebasestorage.app',
  );
}
